first push

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -41,9 +41,7 @@ jobs:
 
           touch firebase_config.ts 
 
-          echo '${{ secrets.FIREBASE_CONFIG }}' > firebase_config.json
-
-          jq empty firebase_config.json > /dev/null 2>&1 || { echo "Invalid JSON"; exit 1; }
+          echo '${{ secrets.FIREBASE_CONFIG }}' | sed 's/^"\|"$//g' | jq '.' > firebase_config.json || { echo "Invalid JSON"; exit 1; }
 
           echo "export const firebaseConfig = " > firebase_config.ts
           cat firebase_config.json >> firebase_config.ts
